blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),


]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('blogs/<int:pk>', views.BlogDetailView.as_view(), name='blog-detail'),
    path('subscribes/', views.SubscribesView.as_view(), name='subscribes'),
    path('subscribes/add/<int:pk>', views.SubscribesAddView.as_view(), name='subscribes-add'),
    path('subscribes/delete/<int:pk>', views.SubscribeDeleteView.as_view(), name='subscribe-delete'),
    path('personal/', views.PersonalView.as_view(), name='personal'),
    path('personal/posts', views.PersonalPostView.as_view(), name='personal-post'),
    path('post/<int:pk>', views.PostView.as_view(), name='post-detail'),
    path('post/create/', views.CreatePostView.as_view(), name='post-create'),
    path('post/update/<int:pk>', views.PostUpdate.as_view(), name='post-update'),
    path('post/delete/<int:pk>', views.PostDelete.as_view(), name='post-delete'),
    path('post/addreadhistory/<int:pk>', views.AddPostReadHistory.as_view(), name='post-addreadhistory'),

]

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = models.EmailField('Адрес электронной почты', max_length=64, unique=True, null=False)
    first_name = models.CharField('Имя', max_length=64, null=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['password', 'first_name']

main/models.py
from django.conf import settings
from django.db import models


class Blog(models.Model):
    title = models.CharField('Название', max_length=128)
    description = models.TextField('Описание', max_length=512)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=64)
    content = models.TextField('Текст', max_length=5120)
    post_time = models.DateTimeField('Время публикации', auto_now_add=True)
    blog = models.ForeignKey(
        'Blog',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title


class Subscription(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    blog = models.ForeignKey(
        'Blog',
        on_delete=models.CASCADE
    )
    subscription_date = models.DateTimeField('Дата подписки', auto_now_add=True)

    def __str__(self):
        return f'Subscription {self.user} on {self.blog}'


class PostReadHistory(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    date_created = models.DateTimeField('Дата прочтения поста', auto_now_add=True)

    def __str__(self):
        return f'{self.post.id}'

main/forms.py
from django import forms

from . import models


class CreateForm(forms.ModelForm):

    class Meta:
        model = models.Post
        fields = ['title', 'content']

authentication/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.views import View
from django.views.generic import DetailView, TemplateView, CreateView, UpdateView

from . import models
from .forms import CreateForm


class IndexView(TemplateView):
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = models.Blog.objects.select_related('user')
        if self.request.user.is_authenticated:
            query = query.exclude(user=self.request.user)
        context['blogs'] = query.all()
        return context


class PostView(TemplateView):
    template_name = 'main/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = models.Post.objects.get(pk=kwargs['pk'])
        return context


class BlogDetailView(DetailView):
    model = models.Blog
    template_name = 'main/blog_detail.html'
    context_object_name = 'blog'


class SubscribesView(LoginRequiredMixin, TemplateView):
    template_name = 'main/subscribes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subscribes'] = (
            models.Subscription.objects
                .select_related('user')
                .filter(user=self.request.user)
                .prefetch_related('blog')
        )
        return context


class SubscribesAddView(View):
    def get(self, request, pk):
        user = request.user
        blog = models.Blog.objects.get(id=pk)
        models.Subscription.objects.get_or_create(blog=blog, user=user)
        return redirect('main:subscribes')


class SubscribeDeleteView(View):
    def get(self, request, pk):
        subscribe = models.Subscription.objects.get(id=pk)
        subscribe.delete()
        return redirect('main:subscribes')


class PersonalView(LoginRequiredMixin, TemplateView):
    template_name = 'main/personal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = (
            models.Post.objects
                .filter(blog__subscription__user=self.request.user)
                .order_by('-post_time')
        )
        readhistory = models.PostReadHistory.objects.filter(user=self.request.user)
        context['readposts'] = [h.post for h in readhistory]
        return context


class PersonalPostView(LoginRequiredMixin, TemplateView):
    template_name = 'main/personal_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = (
            models.Post.objects
                .filter(blog__user=self.request.user)
        )
        return context


class CreatePostView(LoginRequiredMixin, CreateView):
    template_name = 'main/create_post.html'
    form_class = CreateForm
    success_url = '/personal/posts'

    def form_valid(self, form):
        form.instance.blog = models.Blog.objects.get(user=self.request.user)
        return super(CreatePostView, self).form_valid(form)


class PostUpdate(UpdateView):
    model = models.Post
    fields = ['title', 'content']
    template_name_suffix = 'main/post_update_form'
    success_url = '/personal/posts'

    def form_valid(self, form):
        post = models.Post.objects.select_related('blog').select_related('blog__user').get(id=self.kwargs['pk'])
        if post.blog.user == self.request.user:
            return super(PostUpdate, self).form_valid(form)
        raise PermissionDenied()


class PostDelete(LoginRequiredMixin, View):
    def get(self, request, pk):
        post = models.Post.objects.select_related('blog').select_related('blog__user').get(id=pk)
        if post.blog.user == self.request.user:
            post.delete()
            return redirect('main:personal-post')
        raise PermissionDenied()


class AddPostReadHistory(View):
    def get(self, request, pk):
        post = models.Post.objects.select_related('blog').get(id=pk)
        user = self.request.user
        subscription = models.Subscription.objects.get(blog=post.blog, user=user)
        models.PostReadHistory.objects.get_or_create(post=post, user=user, subscription=subscription)
        return redirect('main:personal')

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<a href="{% url 'main:index' %}"><h3>main page</h3></a>
<a href="{% url 'main:personal' %}"><h3>personal page</h3></a>
<a href="{% url 'main:personal-post' %}"><h3>personal post page</h3></a>
<a href="{% url 'main:subscribes' %}"><h3>subscribes page</h3></a>
<body>
{% block content %}
{% endblock %}
</body>
</html>

main/templates/main/blog_detail.html
{% extends 'main/base.html' %}
{% block title %}{{ blog.title }}{% endblock %}

{% block content %}
    <h2>{{ blog.title }}</h2>
    <h1>{{ blog.description }}</h1>
    <a href="{% url 'main:subscribes-add' blog.id %}">follow</a>
    {% for post in blog.post_set.all %}
        <a href="{% url 'main:post-detail' post.id %}"><h1>{{ post.title }}</h1></a>
        <p>{{ post.content }}</p>
        <p>{{ post.post_time }}</p>
    {% endfor %}
{% endblock %}

main/templates/main/create_post.html
{% extends 'main/base.html' %}
{% block title %}create{% endblock %}

{% block content %}
    <form method="post">
        {{ form.as_p }}
        <button type="submit">create new post</button>
    {% csrf_token %}
    </form>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}Main Page{% endblock %}
{% block content %}
    <div>
        {% for blog in blogs %}
            <a href="{% url 'main:blog-detail' blog.id %}">{{ blog.title }}</a><h4>{{ blog.description }}</h4><br>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/personal.html
{% extends 'main/base.html' %}
{% block title %}{% endblock %}

{% block content %}
    <div>
        {% for post in posts %}
            <a href="{% url 'main:post-detail' post.id %}"><h1>{{ post.title }}</h1></a>
            {% if post in readposts %}
                <p>""read""</p>
            {% endif %}
            <p>{{ post.content }}</p>
            <p>{{ post.post_time }}</p>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/personal_post.html
{% extends 'main/base.html' %}
{% block title %}{% endblock %}

{% block content %}
    <a href="{% url 'main:post-create' %} "><p>create post</p></a>
    <div>
        {% for post in posts %}
            <a href="{% url 'main:post-detail' post.id %}"><h1>{{ post.title }}</h1></a>
            <p>{{ post.content }}</p>
            <p>{{ post.post_time }}</p>
        {% endfor %}
    </div>
{% endblock %}

main/templates/main/post_detail.html
{% extends 'main/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.content }}</h1><a href="{% url 'main:post-addreadhistory' post.id %}">read</a>
    {% if request.user == post.blog.user %}
        <a href="{% url 'main:post-update' post.id %}"><p>change</p></a>
        <a href="{% url 'main:post-delete' post.id %}"><p>delete</p></a>
    {% endif %}
{% endblock %}

main/templates/main/postmain/post_update_form.html
{% extends 'main/base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}

main/templates/main/subscribes.html
{% extends 'main/base.html' %}
{% block title %}Subscribes{% endblock %}
{% block content %}
        {% for subscribe in subscribes %}
            <a href="{% url 'main:blog-detail' subscribe.blog.id %}">{{ subscribe.blog.title }}</a>
            <p>{{ subscribe.subscription_date }}</p>
            <a href="{% url 'main:subscribe-delete' subscribe.id %}"><p>dismiss</p></a>
        {% endfor %}

{% endblock %}